### PR TITLE
Instance references aren't stored in ServiceDescriptor if lifetime is Transient

### PR DESCRIPTION
**Pull request by jazzman55**
Do not store references to Transient services

## Description
- Introduced a condition for storing reference to object instance in ServiceDescriptor

## Motivation and Context
- Resolves nanoFramework/Home#1352

## How Has This Been Tested?
Existing unit tests.

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [x] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [ ] I have added new tests to cover my changes.

### CODE REVIEW

**Review by Ellerbach — APPROVED** [review]
Looks good to me. Thanks for providing the fix.

**Comment by Ellerbach** [comment]
@jazzman55 it seems that you have to agree with the CLA policy. Not sure why it's not showing up. Did you receive anything when submitting the PR?

**Comment by jazzman55** [comment]
> @jazzman55 it seems that you have to agree with the CLA policy. Not sure why it's not showing up. Did you receive anything when submitting the PR?

Nope. I remember signing it last year on my first contribution to nanoframework, but not this time.

**Comment by josesimoes** [comment]
@microsoft-github-policy-service rerun

**Comment by josesimoes** [comment]
@dotnet-policy-service rerun

**Comment by josesimoes** [comment]
@jazzman55 please add a comment to this PR like this `@dotnet-policy-service rerun`

**Comment by jazzman55** [comment]
@dotnet-policy-service rerun

**Comment by josesimoes** [comment]
@jazzman55 thanks!
Care to address Sonarcloud complain please?

**Comment by jazzman55** [comment]
> @jazzman55 thanks! Care to address Sonarcloud complain please?

Something funny is going on... When I click on _Code Smell_ it can't find anything. Can we re-run sonar? 
image

**Comment by josesimoes** [comment]
@jazzman55 😯  you are correct! I've just picked there and everything is green... odd... 
Let me rerun the build to try find where this came from.

**Review by bytewizer — APPROVED** [review]
This looks good to me.  Nice catch!

**Comment by josesimoes** [comment]
Ignoring bogus report of code smell by Sonarcloud as there is no other information on the PR analysis there.

**Pull request merged**
