### PR TITLE
Allow constructor injection of an array of a registered servicetype

### PR DESCRIPTION
**Pull request by KlausVcb**
## Description

- Current version of nF DI does not allow injection of an array of a registered servicetype
- This change recognizes the element type of the parameter array type as a registered servicetype

## Motivation and Context

Constructor array injection is a common DI pattern for injection of multiple implementations of an interface (handler pattern)

## How Has This Been Tested?

There is no regression possible since the change only reacts to constructor parameters that are arrays which was not supported before.

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [x] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [x] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [ ] I have added new tests to cover my changes.

### CODE REVIEW

**Comment by CoryCharlton** [comment]
Hello @KlausVcb can you provide some more details on what problem you are trying to solve with this change? Perhaps a small example to show you you would use this.

**Comment by KlausVcb** [comment]
Hi @CoryCharlton,

I use it to inject multiple implementations of an interface, for instance: 

`        interface IAmMiddleware { }
        class MiddlewareA : IAmMiddleware { }
        class MiddlewareB : IAmMiddleware { }

        public void Register(ServiceCollection serviceCollection)
        {
            serviceCollection
                .AddScoped(typeof(IAmMiddleware), typeof(MiddlewareA))
                .AddScoped(typeof(IAmMiddleware), typeof(MiddlewareB));
        }

        class MiddlewareHungry
        {
            public MiddlewareHungry(IAmMiddleware[] middlewares) { }
        }
`

**Comment by KlausVcb** [comment]
It is supported in .net DI as well except for injection through IEnumerable<T> instead of T[]

See here: https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection#service-registration-methods

**Review by CoryCharlton — APPROVED** [review]

**Comment by CoryCharlton** [comment]
Thanks for the example @KlausVcb. I misunderstood the change at first glance.

@josesimoes This looks good to me and is a valued change.

**Review by CoryCharlton — APPROVED** [review]

**Review by josesimoes — APPROVED** [review]
Following @CoryCharlton approval.

**Comment by josesimoes** [comment]
@nfbot updatedependencies

**Pull request merged**
